const LOADING = 'LOADING';
const DARK_MODE = 'DARK_MODE';
const MENU_STATUS = 'MENU_STATUS';
const IS_MOBILE = 'IS_MOBILE';
const CLIENT_WIDTH = 'CLIENT_WIDTH';
const HEADER_HEIGHT = 'HEADER_HEIGHT';
const HEADER_PIN = 'HEADER_PIN';
const CONTENT_HEIGHT = 'CONTENT_HEIGHT';
const INFO = 'INFO';

const ROUTES = 'ROUTES';

const ARTICLE_SHOW_LIST = 'ARTICLE_SHOW_LIST';

export {
  LOADING,
  DARK_MODE,
  MENU_STATUS,
  IS_MOBILE,
  CLIENT_WIDTH,
  HEADER_HEIGHT,
  HEADER_PIN,
  CONTENT_HEIGHT,
  INFO,

  ROUTES,

  ARTICLE_SHOW_LIST,
};
